name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/moregan-installer
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build frontend
        run: python -m pip install --upgrade build

      - name: Build distributions
        run: python -m build

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
